### ISSUE TITLE
Transfer to the enzymejs org?

### ISSUE THREAD

**Issue by ljharb** [enzymejs/enzyme-matchers#340]
Hi!

Now that enzyme is in its own org - https://github.com/enzymejs - do you have any interest in transfering this repo/npm package to it? You'd of course continue to maintain it the same, but it'd make it more discoverable and supported :-).

If you're interested, please lmk what github and npm names to add to the orgs!

**Comment by blainekasten** [comment]
Hey @ljharb!

I don't actually work for Formidable anymore. So it's not really my call. It would be up to @boygirl. I'm content with either approach. This library get's used a lot so I don't think it's necessary. 

To me, it's actually nice letting Formidable own it, because then I'm not the only one maintaining this! (which I've been doing less of lately anyhow)

**Comment by ljharb** [comment]
Totally fair :-) my hope would be that more people could maintain it if it were transferred (since Formidable wouldn't have to be the only bottleneck there), and that Formidable would continue maintaining it as well!

**Comment by ljharb** [comment]
ping @boygirl; any thoughts on this? There's a number of unmerged PRs, for example.

**Comment by Methuselah96** [comment]
@boygirl Can you help us out here? Seems like this project has stalled.

**Comment by boygirl** [comment]
@ljharb apologies for the long delay. I got approval to transfer this project to the enzyme github org if you're still interested in taking it over. Let me know, and I can help with the npm transfer as well.

**Comment by ljharb** [comment]
@boygirl awesome, I'm very interested!

I've added you to the enzymejs github org, and if you `npm owner add ljharb`, i can add it (and you) to the enzyme npm org as well. Thank you!

**Comment by boygirl** [comment]
@ljharb you should be good to go. Let me know if you need anything else.

**Comment by ljharb** [comment]
@boygirl thanks! Looks like i still need npm publish rights. I invited @blainekasten to the enzyme npm org; what's your npm username?

**Comment by boygirl** [comment]
Hmm, you should have publish rights. My npm username is `boygirl`, but that user isn't an owner on these packages. Only `formidable-owner` and `blainekasten`. I logged in as `formidable-owner` via npm's web interface and invited you. Let me triple check. I've have had some issues with updating npm permissions via the web interface before.

**Comment by boygirl** [comment]
Okay, I've added you via the CLI, so you should now have publish rights for `enzyme-matchers`, `jest-enzyme`, and `jasmine-enzyme`. I couldn't add you to `eslint-config-jest-enzyme` or `jest-environment-enzyme` because @blainekasten is the sole owner.

**Comment by ljharb** [comment]
Awesome, thanks! Let me know if you lost any access you need in the process, but I think we should be all set.
